I've sometimes had troubles with boto3 downloads from s3
wherein it expects a `raw` directory, otherwise throwing errors
during `fetch_bucket` like

    ```
      File "/usr/lib/python3.5/site-packages/boto3/s3/transfer.py", line 332, in open
        return open(filename, mode)
    FileNotFoundError: [Errno 2] No such file or directory: 'raw/capitals.csv.350382e0'
    ```

Forcing the `raw` directory to exist seems to hackily avoid this problem.
